# Generated by Django 6.0.7 on 2026-09-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_refund_id_payment_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay Online'), ('cash', 'Cash'), ('card_pos', 'Card POS Swipe'), ('upi_direct', 'Direct UPI Transfer'), ('bank_transfer', 'Direct Bank Transfer'), ('pay_at_checkout', 'Pay at Checkout')], db_index=True, default='razorpay', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
