# Generated by Django 6.0.7 on 2026-09-19 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('event_id', models.CharField(db_index=True, max_length=150)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'processed webhook event',
                'verbose_name_plural': 'processed webhook events',
                'ordering': ['-processed_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'event_id'), name='unique_webhook_event')],
            },
        ),
    ]
