# Generated by Django 5.1.15 on 2026-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_booking_hold_expires_at_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, help_text='Human-readable booking reference (e.g., BK-20260424-A3F7).', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID for this booking.', max_length=100, null=True),
        ),
    ]
