# Generated by Django 5.1.15 on 2026-04-25 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_booking_booking_reference_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Upload a room photo (JPEG/PNG, max 5MB recommended).', upload_to='room_images/')),
                ('caption', models.CharField(blank=True, default='', help_text='Optional caption for the image.', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image is shown as the hero/thumbnail.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order. Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'verbose_name': 'room image',
                'verbose_name_plural': 'room images',
                'ordering': ['order', '-is_primary', 'created_at'],
            },
        ),
    ]
