# Generated by Django 5.1.15 on 2026-05-12 07:25

from django.db import migrations


def seed_property(apps, schema_editor):
    Property = apps.get_model('rooms', 'Property')
    Room = apps.get_model('rooms', 'Room')

    # Create a default seed property
    default_property, created = Property.objects.get_or_create(
        name="Default Property",
        defaults={
            "city": "Unknown City",
            "is_active": True,
        }
    )

    # Assign all existing rooms to this default property
    Room.objects.filter(property__isnull=True).update(property=default_property)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_property_room_property'),
    ]

    operations = [
        migrations.RunPython(seed_property, migrations.RunPython.noop),
    ]
