# Generated by Django 5.1.15 on 2026-05-12 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_booking_status_otablock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Overridden price per night in INR.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rooms.room')),
            ],
            options={
                'verbose_name': 'room rate',
                'verbose_name_plural': 'room rates',
                'ordering': ['start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='rate_end_date_after_start_date')],
            },
        ),
    ]
