# Generated by Django 5.1.15 on 2026-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_roomrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='operational_status',
            field=models.CharField(choices=[('available', 'Available'), ('needs_cleaning', 'Needs Cleaning'), ('maintenance', 'Maintenance')], db_index=True, default='available', help_text='Current operational state of the room.', max_length=20),
        ),
    ]
