# Generated by Django 5.1.15 on 2026-05-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_roomrate 2'),
        ('rooms', '0009_room_operational_status'),
    ]

    operations = [
    ]
