# Generated by Django 6.0.5 on 2026-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_merge_0008_roomrate 2_0009_room_operational_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='GST amount computed from PropertyTaxConfig at confirmation time.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, help_text='Human-readable booking reference (e.g., TT-2026-00001).', max_length=20, null=True, unique=True),
        ),
    ]
