# Generated by Django 6.0.5 on 2026-05-18 02:14

from django.db import migrations, models


def rename_needs_cleaning(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Room.objects.filter(operational_status='needs_cleaning').update(operational_status='cleaning')


def rename_cleaning_back(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Room.objects.filter(operational_status='cleaning').update(operational_status='needs_cleaning')


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_booking_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='operational_status',
            field=models.CharField(choices=[('available', 'Available'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('out_of_order', 'Out of Order')], db_index=True, default='available', help_text='Current operational state of the room.', max_length=20),
        ),
        migrations.RunPython(rename_needs_cleaning, rename_cleaning_back),
    ]
