# Generated by Django 6.0.5 on 2026-06-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_operational_status_expand'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.DecimalField(decimal_places=1, default='4.5', help_text='Guest rating out of 5, shown on property cards.', max_digits=2),
        ),
        migrations.AddField(
            model_name='property',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of guest reviews backing the rating.'),
        ),
    ]
