# Generated by Django 6.0.5 on 2026-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_property_rating_property_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this room in the Featured Stays carousel on the home page.'),
        ),
    ]
