# Generated by Django 6.0.6 on 2026-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_room_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Room rating out of 5. Falls back to property rating if not set.', max_digits=2, null=True),
        ),
    ]
