# Generated by Django 6.0.6 on 2026-06-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_copy_property_rating_to_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='property',
            name='review_count',
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, default='4.5', help_text='Room rating out of 5.', max_digits=2),
        ),
    ]
