# Generated by Django 6.0.6 on 2026-06-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_remove_property_rating_remove_property_review_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
    ]
