# Generated by Django 6.0.5 on 2026-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_remove_property_rating_remove_property_review_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', help_text='Razorpay order ID for this booking.', max_length=100),
        ),
    ]
