# Generated by Django 6.0.7 on 2026-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_alter_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='loyalty_awarded',
            field=models.BooleanField(default=False, help_text='Set once loyalty points have been credited (24h after checkout, stay not cancelled).'),
        ),
    ]
