# Generated by Django 6.0.7 on 2026-09-19 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_booking_loyalty_awarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_bookings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_id_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_id_type',
            field=models.CharField(blank=True, default='', help_text='e.g. Aadhaar, Passport, Driving License', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='operational_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('web', 'Direct Website'), ('walk_in', 'Walk-In Front Desk'), ('phone', 'Phone Reservation'), ('ota_booking_com', 'Booking.com'), ('ota_agoda', 'Agoda'), ('ota_makemytrip', 'MakeMyTrip'), ('ota_airbnb', 'Airbnb'), ('ota_other', 'Other OTA')], db_index=True, default='web', max_length=30),
        ),
    ]
