# Generated by Django 6.0.7 on 2026-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_booking_created_by_staff_booking_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ota_reservation_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Channel Manager / OTA Reservation ID (e.g. Channex/Booking.com/Agoda ID).', max_length=100),
        ),
    ]
