# Generated by Django 6.0.7 on 2026-09-19 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_booking_ota_reservation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in', 'check_out', 'status'], name='idx_bk_rm_dates_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out', 'status'], name='idx_bk_dates_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status', '-created_at'], name='idx_bk_usr_st_created'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['property', 'is_active', 'operational_status'], name='idx_rm_prop_act_status'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'is_active'], name='idx_rm_type_active'),
        ),
    ]
