# Generated by Django 6.0.7 on 2026-09-19 15:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_couponredemptionrule_coupon'),
        ('rooms', '0022_booking_idx_bk_rm_dates_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Loyalty coupon or promo code applied to this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='loyalty.coupon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount deducted from total price.', max_digits=10),
        ),
    ]
