# Generated by Django 6.0.7 on 2026-10-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_booking_coupon_booking_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrate',
            name='closed_to_arrival',
            field=models.BooleanField(default=False, help_text='Guests may not check in on dates in this range.'),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='closed_to_departure',
            field=models.BooleanField(default=False, help_text='Guests may not check out on dates in this range.'),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='max_stay',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum nights allowed for guests whose stay covers this range.', null=True),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='min_stay_arrival',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum nights for guests arriving in this date range (maps to min_stay_arrival in Channex / MLOS on Booking.com).', null=True),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='min_stay_through',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum nights when any stay-night falls in this range (maps to min_stay_through in Channex; leave blank if unsure).', null=True),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='stop_sell',
            field=models.BooleanField(default=False, help_text='Block all OTA sales for this date range.'),
        ),
    ]
