# Generated by Django 6.0.5 on 2026-05-15 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('TEMPLE', 'Temple'), ('BEACH', 'Beach'), ('MUSEUM', 'Museum'), ('RESTAURANT', 'Restaurant'), ('SHOPPING', 'Shopping'), ('NATURE', 'Nature'), ('EVENT', 'Event')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('opening_hrs', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attraction',
                'verbose_name_plural': 'attractions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttractionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='attraction_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.attraction')),
            ],
            options={
                'ordering': ['sort_order', '-is_primary'],
            },
        ),
    ]
