# Generated by Django 6.0.6 on 2026-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='whatsapp_link',
            field=models.URLField(blank=True, default='', help_text='WhatsApp chat or group link for redirections.', max_length=2000),
        ),
    ]
