# Generated by Django 6.0.6 on 2026-06-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attraction_whatsapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='whatsapp_link',
            field=models.URLField(blank=True, default='', help_text='Redirect link for this cause.', max_length=2000),
        ),
    ]
