# Generated by Django 6.0.6 on 2026-06-25 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cause_whatsapp_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.CharField(default='Request to book', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('whatsapp_link', models.URLField(blank=True, default='', help_text='Redirect link for this activity. If empty, uses default WhatsApp message.', max_length=2000)),
                ('whatsapp_message', models.CharField(blank=True, default='', help_text='WhatsApp prefilled message if custom link is not provided.', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
