# Generated by Django 6.0.7 on 2026-09-19 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_page', models.CharField(choices=[('home', 'Homepage Hero'), ('pondicherry', 'Pondicherry Retreat'), ('auroville', 'Auroville Retreat'), ('bengaluru', 'Bengaluru Retreat')], db_index=True, default='home', max_length=50)),
                ('title', models.CharField(help_text='Headline / floating title text', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Supporting tagline', max_length=300)),
                ('image', models.ImageField(help_text='Desktop hero image', upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile crop image', null=True, upload_to='banners/mobile/')),
                ('cta_label', models.CharField(default='Explore Stays', help_text='Call to action button text', max_length=50)),
                ('cta_url', models.CharField(default='/rooms/search/', help_text='Link destination for button', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site banner',
                'verbose_name_plural': 'site banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
