# Generated by Django 6.0.5 on 2026-09-30 13:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitebanner'),
        ('rooms', '0023_booking_coupon_booking_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannexProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channex_property_id', models.UUIDField(help_text='Property UUID as it exists in Channex. Must be globally unique — inbound bookings resolve TTR property from this UUID.', unique=True)),
                ('currency', models.CharField(default='INR', help_text='ISO 4217 currency code Channex expects for this property (the staging test property is USD; production is INR).', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='If off, no ARI changes are recorded or pushed for this property.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channex_mapping', to='rooms.property')),
            ],
            options={
                'verbose_name': 'Channex property mapping',
                'verbose_name_plural': 'Channex property mappings',
            },
        ),
        migrations.CreateModel(
            name='ChannexRoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('deluxe', 'Deluxe')], max_length=10)),
                ('channex_room_type_id', models.UUIDField(help_text='Room type UUID as it exists in Channex. Must be globally unique — inbound bookings resolve TTR room type from this UUID.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_mappings', to='core.channexproperty')),
            ],
            options={
                'verbose_name': 'Channex room-type mapping',
                'verbose_name_plural': 'Channex room-type mappings',
            },
        ),
        migrations.CreateModel(
            name='ChannexRatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Best Available Rate', help_text="Human label for this rate plan (e.g. 'BAR', 'Bed & Breakfast').", max_length=100)),
                ('channex_rate_plan_id', models.UUIDField(help_text='Rate plan UUID as it exists in Channex.', unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='The plan used when a change does not name a specific rate plan. Only one plan per room type may be marked default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='core.channexroomtype')),
            ],
            options={
                'verbose_name': 'Channex rate-plan mapping',
                'verbose_name_plural': 'Channex rate-plan mappings',
            },
        ),
        migrations.CreateModel(
            name='ARIChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('availability', 'Availability'), ('rates', 'Rates'), ('restrictions', 'Restrictions')], max_length=20)),
                ('room_type', models.CharField(help_text='Internal room-type string; resolved to a Channex UUID at push time.', max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(help_text='Exclusive end date of the affected range.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Worker skips this row until now >= next_retry_at (backoff).')),
                ('channex_task_id', models.CharField(blank=True, default='', help_text='Task/response id returned by Channex on a successful push (used as evidence for certification).', max_length=100)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ari_changes', to='core.channexproperty')),
            ],
            options={
                'verbose_name': 'ARI change (outbox)',
                'verbose_name_plural': 'ARI changes (outbox)',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='idx_arichange_status_retry')],
            },
        ),
        migrations.AddConstraint(
            model_name='channexroomtype',
            constraint=models.UniqueConstraint(fields=('property_mapping', 'room_type'), name='uniq_channex_roomtype_per_property'),
        ),
        migrations.AddConstraint(
            model_name='channexrateplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('room_type_mapping',), name='uniq_default_rateplan_per_roomtype'),
        ),
    ]
