# Generated by Django 6.0.5 on 2026-05-16 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0010_merge_0008_roomrate 2_0009_room_operational_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_pts', models.PositiveIntegerField(help_text='Minimum points to reach this tier.')),
                ('discount_pct', models.DecimalField(decimal_places=2, default='0.00', help_text='Discount percentage for guests in this tier.', max_digits=5)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'min_pts'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('multiplier', models.DecimalField(decimal_places=2, default='1.00', help_text='Applied to base points for bookings whose check-in falls in this range.', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(blank=True, help_text='Leave blank to apply across all properties.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_rules', to='rooms.property')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_booking_pts', models.PositiveIntegerField(default=200, help_text="Points for a guest's very first confirmed booking.")),
                ('pts_per_night', models.PositiveIntegerField(default=100, help_text='Points per night for all bookings after the first.')),
                ('monthly_repeat_multiplier', models.DecimalField(decimal_places=2, default='1.50', help_text='Multiplier when guest has ≥2 confirmed bookings in the same calendar month.', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_config', to='rooms.property')),
            ],
            options={
                'verbose_name': 'Loyalty Config',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.IntegerField(help_text='Positive = earned, negative = redeemed/deducted.')),
                ('reason', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('TIER_UPGRADE', 'Tier Upgrade Bonus'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('COUPON_REDEMPTION', 'Coupon Redemption'), ('REFUND_DEDUCTION', 'Refund Deduction')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='rooms.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
