# Generated by Django 6.0.7 on 2026-09-19 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial_loyalty_models'),
        ('rooms', '0022_booking_idx_bk_rm_dates_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponRedemptionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. ₹250 Off Stay Voucher', max_length=100)),
                ('points_cost', models.PositiveIntegerField(help_text='Points required to redeem this coupon')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount (₹)'), ('percentage', 'Percentage (%)')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount in ₹ or %', max_digits=10)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default='0.00', help_text='Minimum booking total required to use this coupon.', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount cap for percentage vouchers.', max_digits=10, null=True)),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='Number of days the coupon remains valid after redemption.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, help_text='Leave blank for platform-wide availability across all properties.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redemption_rules', to='rooms.property')),
            ],
            options={
                'verbose_name': 'Coupon Redemption Rule',
                'verbose_name_plural': 'Coupon Redemption Rules',
                'ordering': ['points_cost', 'discount_value'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount (₹)'), ('percentage', 'Percentage (%)')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('applied', 'Applied to Hold'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owner of the coupon. Null for general public promo codes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('redemption_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_coupons', to='loyalty.couponredemptionrule')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
