# Generated by Django 5.1.15 on 2026-05-12 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0006_auto_20260512_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('employee', 'Employee'), ('super_admin', 'Super Admin')], default='guest', max_length=20)),
                ('fin_level', models.CharField(blank=True, choices=[('A', 'Level A (Full Financial Access)'), ('B', 'Level B (Limited Financial Access)'), ('C', 'Level C (No Financial Access)')], max_length=1, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('assigned_properties', models.ManyToManyField(blank=True, related_name='assigned_employees', to='rooms.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
