# Generated by Django 6.0.5 on 2026-05-13 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email_verified', models.BooleanField(default=False, help_text='Set to True once OTP is successfully verified.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='This pending record expires if not completed in time.')),
            ],
            options={
                'verbose_name': 'pending registration',
                'verbose_name_plural': 'pending registrations',
            },
        ),
    ]
