# Generated by Django 6.0.5 on 2026-07-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_created_by_userprofile_revoked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fin_level',
            field=models.CharField(blank=True, choices=[('A', 'Level A (Full Financial Access)'), ('B', 'Level B (Limited Financial Access)'), ('C', 'Level C (No Financial Access)')], default='', max_length=1),
        ),
    ]
