# Generated by Django 6.0.5 on 2026-05-16 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0010_merge_0008_roomrate 2_0009_room_operational_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_LOCKED', 'Employee Locked'), ('EMPLOYEE_UNLOCKED', 'Employee Unlocked'), ('PASSWORD_RESET', 'Password Reset'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('ROOM_UPDATED', 'Room Updated'), ('TAX_CONFIG_UPDATED', 'Tax Config Updated'), ('LOYALTY_CONFIG_UPDATED', 'Loyalty Config Updated')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, default='7500.00', help_text='Nightly rate threshold (₹). Below → low_rate_pct, at/above → high_rate_pct.', max_digits=10)),
                ('low_rate_pct', models.DecimalField(decimal_places=2, default='12.00', help_text='GST % for rooms priced below the threshold.', max_digits=5)),
                ('high_rate_pct', models.DecimalField(decimal_places=2, default='18.00', help_text='GST % for rooms priced at or above the threshold.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_config', to='rooms.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Tax Config',
            },
        ),
    ]
