# Generated by Django 6.0.5 on 2026-05-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_audit_log_tax_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_LOCKED', 'Employee Locked'), ('EMPLOYEE_UNLOCKED', 'Employee Unlocked'), ('PASSWORD_RESET', 'Password Reset'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_COMPLETED', 'Booking Completed'), ('ROOM_UPDATED', 'Room Updated'), ('ROOM_STATUS_UPDATED', 'Room Status Updated'), ('TAX_CONFIG_UPDATED', 'Tax Config Updated'), ('LOYALTY_CONFIG_UPDATED', 'Loyalty Config Updated'), ('LOYALTY_POINTS_ADJUSTED', 'Loyalty Points Adjusted'), ('PROPERTY_ASSIGNMENT_CHANGED', 'Property Assignment Changed')], max_length=32),
        ),
    ]
