# Generated by Django 6.0.5 on 2026-06-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_LOCKED', 'Employee Locked'), ('EMPLOYEE_UNLOCKED', 'Employee Unlocked'), ('EMPLOYEE_REVOKED', 'Employee Revoked'), ('EMPLOYEE_DELETED', 'Employee Deleted'), ('PASSWORD_RESET', 'Password Reset'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_COMPLETED', 'Booking Completed'), ('PROPERTY_CREATED', 'Property Created'), ('PROPERTY_UPDATED', 'Property Updated'), ('ROOM_CREATED', 'Room Created'), ('ROOM_UPDATED', 'Room Updated'), ('ROOM_STATUS_UPDATED', 'Room Status Updated'), ('ROOM_IMAGE_UPLOADED', 'Room Image Uploaded'), ('ROOM_IMAGE_DELETED', 'Room Image Deleted'), ('TAX_CONFIG_UPDATED', 'Tax Config Updated'), ('LOYALTY_CONFIG_UPDATED', 'Loyalty Config Updated'), ('LOYALTY_CREDIT', 'Loyalty Credit'), ('LOYALTY_DEBIT', 'Loyalty Debit'), ('PROPERTY_ASSIGNMENT_CHANGED', 'Property Assignment Changed')], max_length=32),
        ),
    ]
